# -*- coding: utf-8 -*-
"""World Energy Consumption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNo1hX45_cxiM9koByp6JlLpxCsD-zHO

# World Energy Consumption
"""

import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.plotting import figure, show

#@title Loading Data
LoadCsv = 'https://raw.githubusercontent.com/AshrafulPatHan/notebook/main/World%20Energy%20Consumption/World%20Energy%20Consumption.csv'
data = pd.read_csv(LoadCsv)
data.head()

output_notebook()

#@title year to biofuel_electricity

p = figure(title="year vs biofuel_electricity",width=400, height=400)

p.scatter(data['year'], data['biofuel_electricity'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "year"
p.yaxis.axis_label = "biofuel_electricity"

show(p)

"""## Sort Country"""

High_Population = data[(data['year'] == 2022) & (data['population'] > 160000000)]
High_Population

# 3. Sort the results by population from highest to lowest
sorted_High_Population = High_Population.sort_values(by="population", ascending=False)
sorted_High_Population

"""## Contry Details"""

#@title Add Country Name
CountryName = 'Bangladesh' #@param {type:"string"}
country = data[data['country'] == CountryName].copy()
country

country[['year', 'population']]

display(country['gdp'])

